### ISSUE TITLE
Can you add interfaces to drop-down list?

### ISSUE THREAD

**Issue by Absent83** [SolidAlloy/ClassTypeReference-for-Unity#12]
Can you add **interfaces** to drop-down list?
Now I can check only class and abstract class.

**Comment by SolidAlloy** [comment]
It is not supported yet. I will add support for it soon

**Comment by Absent83** [comment]
Thank you!

**Comment by SolidAlloy** [comment]
Hi, thanks for waiting. I made TypeReference support interfaces but the usage changed quite noticeably. Use it like this to include interfaces in the dropdown:
```
[Inherits(typeof(IGreetingLogger), AllowAbstract = true)]
public TypeReference greetingLoggerType;
```
`AllowAbstract` will include both abstract classes and interfaces in the drop-down menu.
You can also look through Readme to check what else changed.
