### ISSUE TITLE
NullReferenceException for MonoScript asset

### ISSUE THREAD

**Issue by boris47** [SolidAlloy/ClassTypeReference-for-Unity#18]
Hi there,

First of all, i'm really grateful to you for developing this feature, very very very useful for unity, i' use it everywhere(<3).

Unfortunately i'm opening this issue because at first usage of these scripts i found unity editor giving to me this errors
![image](https://user-images.githubusercontent.com/22798998/92245565-d99a7300-eec4-11ea-890c-cceb1a0fa7b8.png)

with the result that my component serialization in inspector is broken as shown in following image
![image](https://user-images.githubusercontent.com/22798998/92245475-b8d21d80-eec4-11ea-91cf-a5b9f9db5864.png)

Unity console lead me to this location(Runtime/TypeReference.cs:132):
![image](https://user-images.githubusercontent.com/22798998/92245661-f636ab00-eec4-11ea-960c-419641b499fd.png)

Possible solution could be the usage of null-conditional operator:
![image](https://user-images.githubusercontent.com/22798998/92245741-123a4c80-eec5-11ea-842f-29bfb91bd4a9.png)

In my case this fix works perfectly.
Thanks in advice.

**Comment by SolidAlloy** [comment]
Thank you, I applied the fix :)
