### ISSUE TITLE
uncomfortable and slow selection in a large project. No drag n drop.

### ISSUE THREAD

**Issue by Absent83** [SolidAlloy/ClassTypeReference-for-Unity#2]
I can recommend to see this realization: MonoScriptAttribute and the associated property drawer (MonoScriptPropertyDrawer).

http://answers.unity.com/answers/1463038/view.html
https://www.dropbox.com/s/i98oazr1cohlbln/MonoScriptAttribute.cs?dl=0
https://www.dropbox.com/s/mn6kkg8f7acxmqu/MonoScriptPropertyDrawer.cs?dl=0

**Comment by SolidAlloy** [comment]
Hi, thanks for the references. I will think of the drag'n'drop implementation.
How big is your project in terms of the number of classes? Is the selection still slow when you narrow the search by using ClassImplements or ClassExtends?

**Comment by SolidAlloy** [comment]
So, I dug the drag'n'drop part a bit, and I'm sure it is possible to implement (for MonoScript-derived classes only, unfortunately.)
However, it will be pretty painful to implement through the standard IMGUI. I would love to implement this through UIElements and even created a template of how I think it should look (how do you like it, by the way?).
![TypeObjectPicker](https://user-images.githubusercontent.com/22909454/88331133-2a02aa80-cd35-11ea-8e1e-265534da5998.png)

Apparently, custom PropertyDrawers implemented through UIElements can be used only with custom Editors implemented through UIElements. It makes UIElements useless for PropertyDrawers. It should be fixed when Inspector is switched to UIElements sometime soon in future versions of Unity. Once it is fixed, I will come back to this request and add the object-picker field unless som kind person implements this through IMGUI by that time.

**Comment by SolidAlloy** [comment]
Hi, thanks for waiting. I added a drop-down interface where you can search for a specific type. It should help to find types quickly and is certainly more comfortable than the built-in GenericMenu interface. Please check it out
