### ISSUE TITLE
Add information about gameObject/prefab/scriptableObject name to logs

### ISSUE THREAD

**Issue by Absent83** [SolidAlloy/ClassTypeReference-for-Unity#20]
Is there an oppotunity to add info about game object (scene, parents, name) / prefab (path, name) to the logs:

![изображение](https://user-images.githubusercontent.com/38653973/99182964-873dc400-2749-11eb-98f0-83e26767c000.png)

There is no oppotunity to point out the gameobject with problem.

**Comment by Absent83** [comment]
In this case problem was in the scriptable object:

![изображение](https://user-images.githubusercontent.com/38653973/99184087-a6405400-2751-11eb-81fd-ae82013cdf11.png)

![изображение](https://user-images.githubusercontent.com/38653973/99184100-bb1ce780-2751-11eb-80ac-0f7d890448d7.png)

![изображение](https://user-images.githubusercontent.com/38653973/99184108-c7a14000-2751-11eb-9cb9-35e0861a31ae.png)

**Comment by SolidAlloy** [comment]
Yeah, I thought of it too, and I agree it is inconvenient. The problem is there is no easy way for a custom serializable class to find what gameObject/asset it is used in. The only way I can think of is to search in all game objects and assets for a type reference with the missing type. Do you have a better idea, perhaps?

**Comment by SolidAlloy** [comment]
Hi, thanks for waiting. I developed a feature that allows searching what objects (scriptable objects, prefabs, scene objects, etc.) contain a certain value. I started using it to check where in the project the missing type is used when TypeReference detects a type was lost. Could you check how it works in your project? I've tested it on a number of cases, but bugs and errors might still exist, especially if the search is performed in a large project, so I will appreciate any feedback.
To start using this feature, please import ClassTypeReference 2.7.0 or later.
