### ISSUE TITLE
The type 'MonoScript' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by Freznosis** [SolidAlloy/ClassTypeReference-for-Unity#22]
Getting this error when installing via UPM or OpenUPM.

`Library\PackageCache\com.solidalloy.util@1.23.0\Editor\Extensions\MonoScriptExtensions.cs(82,35): error CS0012: The type 'MonoScript' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEditor.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
`

Unity 2019.4.18f1, x64, Net 4.x, etc.

**Comment by SolidAlloy** [comment]
Hello, thanks for reporting the error. It was due to Unity 2019 requiring a dependency to UnityEditor.dll instead of UnityEditor.CoreModule.dll. I fixed it, so you can try installing the 2.8.3 version now.
