### ISSUE TITLE
TypeReference dropdown does not respect [Inherits] Attribute constraints

### ISSUE THREAD

**Issue by Kazkoo** [SolidAlloy/ClassTypeReference-for-Unity#23]
The [Inherits] attribute no longer limits types displayed in dropdown. Instead, all types from all namespaces are displayed.
Tested with version 2.8.4 (1.24.0 Utilities)

**Comment by SolidAlloy** [comment]
Hello, thanks for reporting the issue. I checked it in the Usage Example sample, and the types are filtered properly there.
![image](https://user-images.githubusercontent.com/22909454/106661299-b544de80-65a9-11eb-88c4-3cab740b0a3c.png)

Can you import the "Usage Examples" sample into your project and check it there? Perhaps, the issue is caused by a specific set of values, passed to the attribute constructor. I will appreciate it if you provide an example of how you use the Inherits attribute (whether you filter by one or multiple types, whether you use a class or an interface type, etc.)

**Comment by Kazkoo** [comment]
I am only using one constraint, like `[Inherits(typeof(MyType))]`
It used to work but now it does not. Perhaps ...

I'm trying to deal with another issue that might be causing this, DLL conflicts with Cysharp ZString and ZLogger and Type-References. Both you and Cysharp are including system DLLs in the package and they seem to be of different version, resulting in conflicts.

Could you please try to install these packages to see if you have conflicts as well and perhaps suggest a way of fixing them?
https://github.com/Cysharp/ZString
https://github.com/Cysharp/ZLogger

Thanks for help!

**Comment by Kazkoo** [comment]
I made a test in an empty project (2021.1.0b4). Installing ZString OR ZLogger in combination with Type-References results in DLL conflicts. I wrote to them as well but what's your take on this? What is the best solution?

**Comment by SolidAlloy** [comment]
The following workaround seems to work:
1. Remove System.Buffers.dll and System.Runtime.CompilerServices.Unsafe.dll from the Plugins folder.
2. Disable "Auto Reference" and "Validate References" in System.Memory.dll
3. In ZString.asmdef, enable "Override References" and add the following DLLs:
- TypeReferences_System.Buffers.dll
- TypeReference_System.Runtime.CompilerServices.Unsafe.dll
- System.Memory.dll

I tried using both TypeReferences and ZString after that and got no errors in the console. Deleting DLLs in the TypeReferences folder should also work, but it would require making the plugin an embedded package, so deleting DLLs in the Plugins folder is easier.

Let's wait for a reply from Cysharp, they may suggest a better idea.

**Comment by SolidAlloy** [comment]
@Kazkoo Have you got it working with the steps I provided? Is the Inherits attribute issue still there? If so, please check how the Inherits attribute works with the _**Usage Examples**_ sample provided with the package.

**Comment by Kazkoo** [comment]
Yeah, I tried it in an empty project (to rule out DLL conflicts). Here's what I found.
Your examples work, but try to change any of them to inherit from MonoBehavior, not TypeReferenceExample.

For example `public class ExampleUsage : MonoBehaviour`

Go into editor and you have to refresh the drawer - click on other gameobject, then back to the sample. You should see that the Inherits attribute no longer works. Can you please try?

**Comment by SolidAlloy** [comment]
Thanks, I was able to reproduce and fix the bug. You can upgrade to 2.8.5 now.

**Comment by Kazkoo** [comment]
Thanks again for the great support!
