### ISSUE TITLE
Dropdown goes to top left of screen on unity version 2021.1.21f

### ISSUE THREAD

**Issue by Reetro** [SolidAlloy/ClassTypeReference-for-Unity#29]
![image](https://user-images.githubusercontent.com/29167997/136410190-b9767698-6e8e-4837-9167-6e07633090fc.png)
Screen shot says it all the dropdown isn't getting a valid postion so it goes to the top left of screen

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the bug. I tried to reproduce it and positioned the inspector on the left side like in your screenshot, but the dropdown is placed correctly nevertheless. Do you by chance use two monitors? This could cause an issue with the positioning. Does the bug persist if you move the inspector tab to the right side of the display?

**Comment by hsandt** [comment]
Also got the bug, but only for the first few times after adding an Inherits type. After clicking on said dropdown at the topleft, the next times I tried, it was back to its normal place.

And I'm using multi-monitor although my laptop is always closed, so technically I'm using a single monitor.

I've just realised I didn't have the latest version, because I installed the old com.solidalloy.type.references (with a dot) instead of com.solidalloy.type-references (with a hyphen). Let me try the new version...

**Comment by hsandt** [comment]
In the meantime I opened a bug about the README mentioning the wrong namespace: #32

**Comment by SolidAlloy** [comment]
Hi all, thanks for reporting the bug and for waiting. I think I finally fixed it for good. The main issue was EditorWindow.ShowAsDropDown() - it tried to interfere with the placement I sent to it which resulted in the window in the top left corner. I replaced it with EditorWindow.ShowAsContext() which doesn't have such quirks or at least has fewer of them, and looks just the same. I now have a multi-monitor setup too and haven't had any issues with the dropdown placement recently, so hopefully the bug doesn't reoccur.

**Comment by hsandt** [comment]
Thanks, I don't find the corresponding commit, could you mention it here manually? (if you write "fix #XXX" in the commit message it should auto-link to this issue too, but I guess it's better not to amend past commit messages at this point)

**Comment by SolidAlloy** [comment]
It was part of a bigger task where I refactored and separated the dropdown API into its own package - [UnityDropdown](https://github.com/SolidAlloy/UnityDropdown).
The particular commit where I removed `ShowAsDropDown()` is [this one](https://github.com/SolidAlloy/UnityDropdown/commit/5da2f6fbd72679e4e7269280d1b7f2153af02c97).
Thanks for the commit message tip, didn't know it!
