### ISSUE TITLE
Needs an option to disallow Null

### ISSUE THREAD

**Issue by phobos2077** [SolidAlloy/ClassTypeReference-for-Unity#3]
Needs an option to remove "null" from the dropdown list so we have to select a type.

**Comment by SolidAlloy** [comment]
Hi, thanks for the feedback. I added an option to remove (None) from the dropdown so that it cannot be chosen from the inspector. Note that the type can still be null by default or if set through code.

**Comment by phobos2077** [comment]
Wow, thank you!
