### ISSUE TITLE
README still references old package name com.solidalloy.type.references

### ISSUE THREAD

**Issue by hsandt** [SolidAlloy/ClassTypeReference-for-Unity#32]
After noticing that GitHub had more recent releases than my UPM-installed version, I've noticed that there are two packages available on upm:

1. com.solidalloy.type.references with latest: 2.8.0 (the old one)
2. com.solidalloy.type-references with latest: 2.11.5 (the correct one)

It must be due to package namespace renaming that left an old reference for retrocompatibility. The old namespace doesn't even have a page on UPM website, only the new name has a URL: https://openupm.com/packages/com.solidalloy.type-references/

So it would be nice to change the README to reflect the new name, and also add a warning about the old name in case some people search it manually with openupm-cli and pick the wrong one.

**Comment by hsandt** [comment]
If you'd rather have all developers use the new namespace than have retrocompatibility, consider a full unpublish (https://openupm.com/docs/opt-out.html) and expect developers to go back to this page to understand what changed.

**Comment by SolidAlloy** [comment]
Hi, thanks for noticing the problem. Can't imagine how many more people used the old package and didn't receive any updates! I fixed it in README.

I changed the name of the package as per this guide https://openupm.com/docs/modifying-upm-package.html
But I had no idea it was left in CLI! I'll contact the OpenUPM developer regarding this. Hopefully, no one else finds the old package from now on.

**Comment by hsandt** [comment]
For reference, the commit adding correct package full name to README: e6f7a38e30c78931a577b275fd5ee70b7b337796
