### ISSUE TITLE
Cant import sample

### ISSUE THREAD

**Issue by thewhitewayofdelight** [SolidAlloy/ClassTypeReference-for-Unity#35]
Helppp
I just installed the package via openupm to a fresh Unity 2020.2 project, then adding samples to the project. And got these errors.

I use version 2.13.0 - February 08, 2022
Thank you!

<img width="751" alt="Screen Shot 2022-03-02 at 00 06 22" src="https://user-images.githubusercontent.com/87333145/156214976-c768f32a-2e80-429f-8812-239facd5b62e.png">

**Comment by SolidAlloy** [comment]
Thank you for noticing it, I've fixed the samples. Please update the package and try importing it again.
