### ISSUE TITLE
ExcludeNone feature bronen in latest release

### ISSUE THREAD

**Issue by Kazkoo** [SolidAlloy/ClassTypeReference-for-Unity#36]
Hi, after upgrading to newest release, the "Inherits" attribute no longer recognizes ExcludeNone parameter.

**Comment by SolidAlloy** [comment]
Hi, sorry, it was reckless for me to just change the parameter name. I've now added back the ExcludeNone parameter and marked it as obsolete. The new parameter name is **ShowNoneElement** which is `true` by default.
