### ISSUE TITLE
Cannot install due to to invalid dependencies

### ISSUE THREAD

**Issue by ppStarLightShadows** [SolidAlloy/ClassTypeReference-for-Unity#37]
> [Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git]:
>   Package com.solidalloy.type-references@https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git has invalid dependencies or related test packages:
>     com.solidalloy.unity-dropdown (dependency): Package [com.solidalloy.unity-dropdown@1.1.1] cannot be found [NotFound].
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

> [Package Manager Window] Error adding package: https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git.
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

Note: Yes, I did install SolidUtilities first. Currently, SolidUtilities has its own error preventing it from compiling correctly, which I have submitted an issue for on SolidUtilities's page. That may possibly be because of this error.

**Comment by SolidAlloy** [comment]
Thanks for reporting the issue. I updated the dependencies some time ago but didn't change the installation instructions. I updated them now, so please try installing the package once again.

### The new installation section from README:
To install the project as a Git package do the following:

1. In Unity, open **Project Settings** -> **Package Manager**.
2. Add a new scoped registry with the following details:
   - **Name**: package.openupm.com
   - **URL**: https://package.openupm.com
   - Scope(s):
     - com.openupm
     - com.solidalloy
     - org.nuget
3. Hit **Apply**.
4. Go to **Window** -> **Package Manager**.
5. Press the **+** button, *Add package from git URL*.
6. Enter **com.solidalloy.type-references**, press **Add**.
