### ISSUE TITLE
GUID conflict

### ISSUE THREAD

**Issue by sandsalamand** [SolidAlloy/ClassTypeReference-for-Unity#39]
This issue was closed in 2020, but it seems to still be present now. I installed the package using the Unity Package Manager instructions, and it seems to compile and work just fine, but these error messages reappear on every run of the game.

GUID [e7be1c9624387604fba4005ccf7dbd5a] for asset 'Packages/com.solidalloy.util/Runtime/SerializableCollections/SerializableDictionary.cs' conflicts with:
  'Assets/SerializableDictionary/SerializableDictionary.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

GUID [91da51d02ab9ebc459d80d5965d40d19] for asset 'Packages/com.solidalloy.util/Editor/PropertyDrawers/SerializableDictionaryPropertyDrawer.cs' conflicts with:
  'Assets/SerializableDictionary/Editor/SerializableDictionaryPropertyDrawer.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting it. I fixed the conflict in the [2.16.0](https://github.com/SolidAlloy/ClassTypeReference-for-Unity/releases/tag/2.16.0) version.
