### ISSUE TITLE
[ClassExtends(typeof(T)] on Lists not rendering properly in editor window

### ISSUE THREAD

**Issue by kgc00** [SolidAlloy/ClassTypeReference-for-Unity#5]
Hi,

It seems like this is valid: 
```
public class UnitSpawnData : ScriptableObject
    {
        ...
        [SerializeField, ClassExtends(typeof(UnitModifier))] public List<ClassTypeReference> modifiers;
    }
```
(No errors are thrown when I execute code to add / remove items from the list).  However...

Expected behaviour:
`[SerializeField, ClassExtends(typeof(UnitModifier))] public List<ClassTypeReference> modifiers;`
will allow me to add and remove child classes of UnitModifier in the inspector.

Actual behaviour:
My inspector drawer for the `modifiers` list contains: `None` and nothing else.  
![image](https://user-images.githubusercontent.com/15132641/87465818-1daa7f00-c5ca-11ea-90a2-4570d73f650a.png)

**Comment by SolidAlloy** [comment]
Hi, I cannot reproduce this. A list renders the same options as a single field for me. Does the drop-down contain more classes when you use a single field? If not, ClassTypeReference has a problem discovering UnitModifier-derived classes

**Comment by kgc00** [comment]
Hi, just saw the comment.  I will check tonight when I am off work.  Thanks!

**Comment by kgc00** [comment]
Hi, i think the issue was something on my end =x

I just tried adding a single class as well as a list of classes and they both contained entries:

![image](https://user-images.githubusercontent.com/15132641/88351122-286fbd00-cd0a-11ea-8bd3-6bf495b8cc0f.png)

**Comment by kgc00** [comment]
I see.  So on the original script i had posted about, we still have the issue:

![image](https://user-images.githubusercontent.com/15132641/88351223-6cfb5880-cd0a-11ea-8c10-00580c28151a.png)

the only thing i can think of is that this later class (unit spawn data) is a scriptable object while the former (arena manager) was a monobehaviour

**Comment by SolidAlloy** [comment]
Great, thanks for digging deeper into this. Glad you made it work with ArenaManager.

There should be no difference for MonoBehaviours and ScriptableObjects. ClassTypeReference lists only the types accessible to the declaring class. In case of UnitSpawnData, it means the types from its own assembly and from all the assemblies referenced by UnitSpawnData's assembly. Perhaps, ArenaManager has access to Modifiers.SpawnModifiers while UnitSpawnData does not. You might also make sure that the classes you want to assign are not internal if they are in a different assembly.
That's all the ideas I have as to why this happened

**Comment by kgc00** [comment]
Thanks for the tips!  Yeah... it was the fact the the UnitSpawnData's assembly did not know about the Modifier's assembly!

**Comment by SolidAlloy** [comment]
Glad to know you resolved it!
