### ISSUE TITLE
UPM reference breaks after every update

### ISSUE THREAD

**Issue by phobos2077** [SolidAlloy/ClassTypeReference-for-Unity#6]
![изображение](https://user-images.githubusercontent.com/4744345/87665492-b3334380-c76f-11ea-84b9-e1aa5c175bc0.png)

I get this error for the second time now after I started using your package a couple of weeks ago. Looks like every time you post an update, reference gets broken. Are you force-pushing and removing commits by any chance?

My manifest.json:
`"com.solidalloy.type.references": "https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git#upm",`

My packages-lock.json:
```
"com.solidalloy.type.references": {
      "version": "https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git#upm",
      "depth": 0,
      "source": "git",
      "dependencies": {},
      "hash": "ee232e4028c8d8e6ad9b55c26828fcbefc924fc2"
    },
```

**Comment by phobos2077** [comment]
I had to fork the repo and use my fork instead to keep this dependency from breaking again. Probably a good idea to resolve this for future users :)

**Comment by SolidAlloy** [comment]
Hmm, this worked before. Moreover, it seems not to happen everytime I push. I will investigate it before pushing to the repo again.

**Comment by phobos2077** [comment]
Note that in recent Unity versions they've added packages-lock.json file which locks into a specific git commit by hash (automatically). Because you seem to rewrite your entire commit history on every update, this naturally breaks because hashes of every commit beyond the point you've rewritten are changed.

**Comment by SolidAlloy** [comment]
The interesting thing here is that even though Unity had packages-lock.json, it never checked out those commits, at least until the 2019.4.1 version I am using now. So, even though I've been force-pushing to the upm branch, and it has been overwriting the commit history, it never bothered Unity. What version of Unity are you using? Perhaps, Unity finally started using packages-lock.json to check out packages or verify their integrity.

**Comment by SolidAlloy** [comment]
I changed the structure of the project in _master_ so that it can be added as a UPM package right away, without GitHub Actions. There shouldn't be any force pushes and commit history changes from now on, and you can install the package using https://github.com/SolidAlloy/ClassTypeReference-for-Unity.git
