### ISSUE TITLE
Not working due to GUID conflicts in meta files

### ISSUE THREAD

**Issue by phobos2077** [SolidAlloy/ClassTypeReference-for-Unity#7]
`GUID [19ddc7d736e94dd4853498fdde12dfab] for asset 'Packages/com.solidalloy.type.references/Editor/TypeDropDownDrawer.cs' conflicts with:
  'Packages/com.solidalloy.type.references/Editor/TypeDropDown.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
`

`GUID [c0e325679500419d8f39d99aba58baba] for asset 'Packages/com.solidalloy.type.references/Editor/TypeFieldDrawer.cs' conflicts with:
  'Packages/com.solidalloy.type.references/Editor/TypeField.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.`

**Comment by SolidAlloy** [comment]
Oops, fixed, thanks for reporting
